# Generated by Django 3.0.5 on 2020-05-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_for_question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_for_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Class'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_for_section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Section'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='student_class',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Class'),
        ),
    ]
