# Generated by Django 3.0.5 on 2020-05-23 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20200519_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_for_section',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_section',
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 16, 58, 10, 704716, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 16, 58, 10, 704194, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
