# Generated by Django 3.0.5 on 2020-05-23 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200523_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_by_teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='classroom.Teacher'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 9, 10, 407722, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 9, 10, 407154, tzinfo=utc), verbose_name='date published'),
        ),
    ]
