# Generated by Django 3.0.5 on 2020-05-23 17:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200523_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 11, 0, 732002, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 23, 17, 11, 0, 731433, tzinfo=utc), verbose_name='date published'),
        ),
    ]
