# Generated by Django 3.0.5 on 2020-05-25 03:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200525_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 3, 27, 18, 451558, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 3, 27, 18, 451007, tzinfo=utc), verbose_name='date published'),
        ),
    ]
